# Generated by Django 4.0.6 on 2022-08-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_player_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cell_status',
            field=models.JSONField(help_text='game cell status', max_length=100, null=True, verbose_name='game cell status'),
        ),
    ]
